version: '3.5'

services:

  mongo:
    image: "mongo:latest"
    container_name: "mongo_cluster"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=testdb
      - MONGO_INITDB_ROOT_USERNAME=test1
      - MONGO_INITDB_ROOT_PASSWORD=test1
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./volumes/mongo_volume:/data/db
    ports:
      - 27020:27017
    networks:
      - mongo_cluster_net

networks:
  mongo_cluster_net:
    driver: bridge
